img=imread('f1.png');
figure;
subplot(5,6,1);
imshow(img);
title('Original');
img=rgb2gray(img);
Im=imresize(img,[50,50]);
Im=imbinarize(Im);
subplot(5,6,2);
imshow(Im);
title('Binary');
X=strel('disk',5);
B=imdilate(imerode(Im,X),X);
subplot(5,6,3);
imshow(B);
title('Palm');
finger= Im-B;
subplot(5,6,4);
imshow(finger);
title('Finger(Noisy)');
n_less=bwareaopen(finger,5);
subplot(5,6,5);
imshow(n_less);
title('Finger(Noiseless)');
Final=(bwlabel(n_less));
Final= max(Final(:));
pos = [10 10];
blank_img = ones(50,50);
blank_img(:,:) = 1;
fig_num = insertText(blank_img,pos,Final,'BoxColor','white');
subplot(5,6,6);
imshow(fig_num);
title('Number of finger');



img=imread('f2.png');
subplot(5,6,7);
imshow(img);
title('Original');
img=rgb2gray(img);
Im=imresize(img,[50,50]);
Im=imbinarize(Im);
subplot(5,6,8);
imshow(Im);
title('Binary');
X=strel('disk',5);
B=imdilate(imerode(Im,X),X);
subplot(5,6,9);
imshow(B);
title('Palm');
finger= Im-B;
subplot(5,6,10);
imshow(finger);
title('Finger(Noisy)');
n_less=bwareaopen(finger,5);
subplot(5,6,11);
imshow(n_less);
title('Finger(Noiseless)');
Final=(bwlabel(n_less));
Final= max(Final(:));
pos = [10 10];
blank_img = ones(50,50);
blank_img(:,:) = 1;
fig_num = insertText(blank_img,pos,Final,'BoxColor','white');
subplot(5,6,12);
imshow(fig_num);
title('Number of finger');



img=imread('f3.png');
subplot(5,6,13);
imshow(img);
title('Original');
img=rgb2gray(img);
Im=imresize(img,[50,50]);
Im=imbinarize(Im);
subplot(5,6,14);
imshow(Im);
title('Binary');
X=strel('disk',5);
B=imdilate(imerode(Im,X),X);
subplot(5,6,15);
imshow(B);
title('Palm');
finger= Im-B;
subplot(5,6,16);
imshow(finger);
title('Finger(Noisy)');
n_less=bwareaopen(finger,5);
subplot(5,6,17);
imshow(n_less);
title('Finger(Noiseless)');
Final=(bwlabel(n_less));
Final= max(Final(:));
pos = [10 10];
blank_img = ones(50,50);
blank_img(:,:) = 1;
fig_num = insertText(blank_img,pos,Final,'BoxColor','white');
subplot(5,6,18);
imshow(fig_num);
title('Number of finger');



img=imread('f4.png');
subplot(5,6,19);
imshow(img);
title('Original');
img=rgb2gray(img);
Im=imresize(img,[50,50]);
Im=imbinarize(Im);
subplot(5,6,20);
imshow(Im);
title('Binary');
X=strel('disk',5);
B=imdilate(imerode(Im,X),X);
subplot(5,6,21);
imshow(B);
title('Palm');
finger= Im-B;
subplot(5,6,22);
imshow(finger);
title('Finger(Noisy)');
n_less=bwareaopen(finger,5);
subplot(5,6,23);
imshow(n_less);
title('Finger(Noiseless)');
Final=(bwlabel(n_less));
Final= max(Final(:));
pos = [10 10];
blank_img = ones(50,50);
blank_img(:,:) = 1;
fig_num = insertText(blank_img,pos,Final,'BoxColor','white');
subplot(5,6,24);
imshow(fig_num);
title('Number of finger');


img=imread('f5.png');
subplot(5,6,25);
imshow(img);
title('Original');
img=rgb2gray(img);
Im=imresize(img,[50,50]);
Im=imbinarize(Im);
subplot(5,6,26);
imshow(Im);
title('Binary');
X=strel('disk',5);
B=imdilate(imerode(Im,X),X);
subplot(5,6,27);
imshow(B);
title('Palm');
finger= Im-B;
subplot(5,6,28);
imshow(finger);
title('Finger(Noisy)');
n_less=bwareaopen(finger,5);
subplot(5,6,29);
imshow(n_less);
title('Finger(Noiseless)');
Final=(bwlabel(n_less));
Final= max(Final(:));
pos = [10 10];
blank_img = ones(50,50);
blank_img(:,:) = 1;
fig_num = insertText(blank_img,pos,Final,'BoxColor','white');
subplot(5,6,30);
imshow(fig_num);
title('Number of finger');